server:
  port: 8080

spring:
  application:
    name: odds-aggregator

logging:
  level:
    com.miraiedge.oddsaggregator : INFO
    org.springframework.scheduling: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/odds-aggregator.log

app:
  odds:
    poll-interval: 5000
    mock-sources:
      - http://localhost:8080/mock/source1/odds
      - http://localhost:8080/mock/source2/odds